import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: '#0A0A0A' },
  splash: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0A0A0A' },
  scrollContent: { flexGrow: 1, justifyContent: 'center', backgroundColor: '#0A0A0A', paddingHorizontal: 20, paddingVertical: 40 },
  card: { width: '100%', maxWidth: 460, alignSelf: 'center', backgroundColor: '#111111', padding: 28, gap: 16, borderRadius: 28, borderWidth: 1, borderColor: '#1E1E1E' },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  logoBox: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#1A1A1A', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#2C2C2E' },
  logoImage: { width: 28, height: 28, borderRadius: 8 },
  brandBlack: { color: '#FFFFFF', fontWeight: '900', fontSize: 18, letterSpacing: 1.5 },
  brandRed: { color: '#E5192A', fontWeight: '900', fontSize: 18, letterSpacing: 1.5 },
  titleRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
  title: { color: '#FFFFFF', fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  titleAccent: { color: '#E5192A', fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  subtitle: { color: '#888', fontSize: 14, lineHeight: 21, marginTop: -6 },
  fieldGroup: { gap: 8 },
  label: { color: '#AAAAAA', fontSize: 13, fontWeight: '600', letterSpacing: 0.3 },
  inputWrapper: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderRadius: 14, backgroundColor: '#1A1A1A', overflow: 'hidden' },
  input: { flex: 1, height: 52, color: '#FFFFFF', paddingHorizontal: 16, fontSize: 15, backgroundColor: 'transparent' },
  eyeBtn: { paddingHorizontal: 14, height: 52, alignItems: 'center', justifyContent: 'center' },
  eyeIcon: { fontSize: 18 },
  fieldError: { color: '#EF4444', fontSize: 12, marginTop: -2 },
  apiError: { color: '#FCA5A5', backgroundColor: '#2A0A0A', borderRadius: 12, padding: 12, lineHeight: 20, fontSize: 13, borderWidth: 1, borderColor: '#7F1D1D' },
  button: { height: 54, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E5192A', borderRadius: 14, marginTop: 4 },
  buttonPressed: { opacity: 0.7 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  googleButton: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: '#1A1A1A', borderWidth: 1.5, borderColor: '#2C2C2E', borderRadius: 14 },
  googleIcon: { color: '#FFFFFF', fontSize: 18, fontWeight: '800' },
  googleButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: -4 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#222' },
  dividerText: { color: '#555', fontSize: 13 },
  forgotWrapper: { alignSelf: 'flex-end', marginTop: -4 },
  forgotLink: { color: '#E5192A', fontSize: 13, fontWeight: '600' },
  link: { color: '#E5192A', fontWeight: '700', fontSize: 14 },
  textButton: { alignSelf: 'center', paddingVertical: 4 },
  footerRow: { flexDirection: 'row', alignSelf: 'center', alignItems: 'center', marginTop: -4 },
  footerText: { color: '#666', fontSize: 14 },
  termsText: { color: '#666', fontSize: 12, lineHeight: 18, textAlign: 'center' },
  notice: { backgroundColor: '#0A1A2A', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#1E3A5F' },
  noticeText: { color: '#60A5FA', lineHeight: 21, fontSize: 13 },
  backBtn: { alignItems: 'center', paddingVertical: 10 },
  backBtnText: { color: '#888', fontSize: 14, fontWeight: '600' },
  home: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0A0A0A', padding: 32, gap: 12 },
  homeLogoBox: { width: 80, height: 80, borderRadius: 24, backgroundColor: '#1A1A1A', alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#2C2C2E', marginBottom: 8 },
  homeLogoImage: { width: 58, height: 58, borderRadius: 16 },
  homeWelcome: { color: '#888', fontSize: 18, fontWeight: '500' },
  homeName: { color: '#FFFFFF', fontSize: 32, fontWeight: '900' },
  homeCopy: { color: '#555', fontSize: 15 },
  signOutBtn: { marginTop: 20, height: 50, paddingHorizontal: 40, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#E5192A', borderRadius: 14 },
  signOutText: { color: '#E5192A', fontWeight: '700', fontSize: 15 },
});
