from flask import Blueprint
from ..auth.decorators import jwt_required
from ..controllers import notificaciones_controller

notificaciones_bp = Blueprint('notificaciones', __name__)

@notificaciones_bp.get('')
@jwt_required()
def mis_notificaciones(): return notificaciones_controller.mis_notificaciones()
@notificaciones_bp.get('/no-leidas/count')
@jwt_required()
def conteo_no_leidas(): return notificaciones_controller.conteo_no_leidas()
@notificaciones_bp.patch('/<int:notificacion_id>/leer')
@jwt_required()
def marcar_como_leida(notificacion_id): return notificaciones_controller.marcar_como_leida(notificacion_id)
@notificaciones_bp.patch('/marcar-todas-leidas')
@jwt_required()
def marcar_todas_como_leidas(): return notificaciones_controller.marcar_todas_como_leidas()
@notificaciones_bp.get('/<int:notificacion_id>')
@jwt_required()
def detalle_notificacion(notificacion_id): return notificaciones_controller.detalle_notificacion(notificacion_id)
@notificaciones_bp.get('/tipos')
@jwt_required()
def tipos_notificacion(): return notificaciones_controller.tipos_notificacion()
@notificaciones_bp.post('/admin')
@jwt_required(roles=['admin'])
def crear_notificacion_admin(): return notificaciones_controller.crear_notificacion_admin()
@notificaciones_bp.get('/admin')
@jwt_required(roles=['admin'])
def admin_notificaciones(): return notificaciones_controller.admin_notificaciones()
@notificaciones_bp.get('/admin/<int:notificacion_id>')
@jwt_required(roles=['admin'])
def admin_notificacion_detalle(notificacion_id): return notificaciones_controller.admin_notificacion_detalle(notificacion_id)
@notificaciones_bp.patch('/admin/<int:notificacion_id>')
@jwt_required(roles=['admin'])
def admin_actualizar_notificacion(notificacion_id): return notificaciones_controller.admin_actualizar_notificacion(notificacion_id)
