CREATE DATABASE IF NOT EXISTS jenna_car;
USE jenna_car;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(180) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role ENUM('client','admin','mechanic') DEFAULT 'client', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE clients (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT UNIQUE NOT NULL, phone VARCHAR(30), address VARCHAR(255), FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE vehicles (id INT AUTO_INCREMENT PRIMARY KEY, client_id INT NOT NULL, brand VARCHAR(80) NOT NULL, model VARCHAR(80) NOT NULL, year SMALLINT, plate VARCHAR(20) UNIQUE NOT NULL, mileage INT DEFAULT 0, FOREIGN KEY (client_id) REFERENCES clients(id));
CREATE TABLE services (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, description TEXT, price DECIMAL(10,2) NOT NULL, duration_minutes INT DEFAULT 60, active BOOLEAN DEFAULT TRUE);
CREATE TABLE appointments (id INT AUTO_INCREMENT PRIMARY KEY, client_id INT NOT NULL, vehicle_id INT NOT NULL, service_id INT NOT NULL, scheduled_at DATETIME NOT NULL, status ENUM('pending','confirmed','completed','cancelled') DEFAULT 'pending', notes TEXT, FOREIGN KEY (client_id) REFERENCES clients(id), FOREIGN KEY (vehicle_id) REFERENCES vehicles(id), FOREIGN KEY (service_id) REFERENCES services(id));
CREATE TABLE work_orders (id INT AUTO_INCREMENT PRIMARY KEY, client_id INT NOT NULL, vehicle_id INT NOT NULL, status ENUM('open','in_progress','ready','closed') DEFAULT 'open', diagnosis TEXT, total DECIMAL(10,2) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES clients(id), FOREIGN KEY (vehicle_id) REFERENCES vehicles(id));
CREATE TABLE receipts (id INT AUTO_INCREMENT PRIMARY KEY, work_order_id INT NOT NULL, subtotal DECIMAL(10,2) NOT NULL, tax DECIMAL(10,2) NOT NULL, total DECIMAL(10,2) NOT NULL, issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (work_order_id) REFERENCES work_orders(id));
CREATE TABLE maintenance_history (id INT AUTO_INCREMENT PRIMARY KEY, vehicle_id INT NOT NULL, service_id INT NOT NULL, performed_at DATETIME NOT NULL, mileage INT, notes TEXT, FOREIGN KEY (vehicle_id) REFERENCES vehicles(id), FOREIGN KEY (service_id) REFERENCES services(id));
