import { FormEvent, useEffect, useState } from 'react'
import { getApiUrl } from '@/lib/config'
const apiUrl = getApiUrl('')
export default function ResetPasswordPage() {
  const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(false)
  useEffect(() => { const query = new URLSearchParams(window.location.search); setEmail(query.get('email') || ''); setCode(query.get('code') || '') }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); const password = String(form.get('password') || ''); if (password.length < 8 || password !== form.get('confirmation')) return setError('Las contraseñas deben coincidir y tener al menos 8 caracteres.'); const response = await fetch(`${apiUrl}/api/auth/reset-password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), code: form.get('code'), password }) }); const data = await response.json(); if (!response.ok) return setError(data.error || 'No fue posible actualizar la contraseña.'); setSuccess(true) }
  return <main className="min-h-screen bg-primary px-6 py-8 text-primary-foreground sm:px-12"><div className="mx-auto flex min-h-screen max-w-md flex-col justify-center"><a href="/sign-in" className="mb-12 text-xs text-primary-foreground/60">← Volver al acceso</a><p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-accent">Recuperar acceso</p><h1 className="mt-4 font-serif text-5xl">Nueva contraseña.</h1>{success ? <div className="mt-8 border border-accent/30 bg-accent/10 p-4 text-sm">Contraseña actualizada correctamente. <a className="text-accent underline" href="/sign-in">Iniciar sesión</a></div> : <form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-xs">Correo electrónico<input name="email" required readOnly type="email" value={email} className="bg-field p-4 text-primary" /></label><label className="grid gap-2 text-xs">Código de recuperación<input name="code" required readOnly value={code} className="bg-field p-4 text-primary" /></label><label className="grid gap-2 text-xs">Nueva contraseña<input name="password" required minLength={8} type="password" className="bg-field p-4 text-primary" /></label><label className="grid gap-2 text-xs">Confirmar contraseña<input name="confirmation" required minLength={8} type="password" className="bg-field p-4 text-primary" /></label><button className="bg-accent p-4 text-xs font-semibold tracking-[0.18em] text-accent-foreground">ACTUALIZAR CONTRASEÑA</button>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}</form>}</div></main>
}
